### ISSUE TITLE
Different messages for different users

### ISSUE THREAD

**Issue by otajor** [kasaromi/chatto#57]
Noticed this strange effect here:
User view 1:
<img width="373" alt="screen shot 2016-02-26 at 10 44 55" src="https://cloud.githubusercontent.com/assets/13705650/13350130/1cd14088-dc76-11e5-905a-8bb0308c0985.png">
User 2 view:
<img width="370" alt="screen shot 2016-02-26 at 10 45 06" src="https://cloud.githubusercontent.com/assets/13705650/13350131/1e47f5a6-dc76-11e5-93f4-01ff0e479a71.png">

For one user, Andrew's comment appears twice and OTM's last comment is empty - for the other, the comment only appears once, and OTM's last comment is '?'

Not sure why this is happening.

**Comment by katbow** [comment]
I'm not sure how to replicate this without many users...how did you guys end up fixing it?

**Comment by otajor** [comment]
Hmm yeah it was weird. We never saw it happening on our chat, but we did fix the thing with the missing messages I think...

Wanna mark it 'won't fix'?

**Comment by katbow** [comment]
it seemed okay after a while when we were using it again so I'm not really sure what happened. I'll close for now!
