### ISSUE TITLE
Organise file structure

### ISSUE THREAD

**Issue by samhstn** [kasaromi/chatto#6]
I think a great file structure would be:

.gitignore (containing node_modules)
favicon.ico
node_modules
coverage (Istanbul puts this in the root by default)
front:
- index.html
- index.js (We need to make a xhr request in this file)
- style.css
- tests:
- \* jasmine (Test the xhr request and dom manipulation functions)

back:
- server.js
- socket.js (putting this seperately because handler function in server.js is going to be quite large)
- redis.js
- tests:
- \* serverTest.js (Use tape and shot)
- \* redisTest.js (Use wrapping-tape - look in to what this is [Elias readme](https://github.com/FAC7/READMEs/tree/master/week5/redis-testing) is a great resourse)

**Comment by samhstn** [comment]
I think its good to sort this out sooner rather than later as its going to be a hassle to make sure each link is changed when if we edit this at the end

**Comment by MyPitit** [comment]
Yes, I agree @shouston3

**Comment by samhstn** [comment]
Great work @katbow
