### ISSUE TITLE
Biiiiig for loop

### ISSUE THREAD

**Issue by otajor** [kasaromi/chatto#60]
https://github.com/kasaromi/chatto/blob/master/index.js#L29-L39

Is there a way to do this with fewer variables/using an array method?

**Comment by samhstn** [comment]
Well spotted, I was hoping nobody would notice

**Comment by samhstn** [comment]
@oturnermajor Thanks for the help with trying to solve the problem

**Comment by otajor** [comment]
Gonna close this as a 'won't fix'
